[program:prosartisan-scheduler]
process_name=%(program_name)s
command=php /var/www/prosartisan/backend-proartisan/artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/prosartisan-scheduler.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=60
stopsignal=TERM
