[program:prosartisan-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/prosartisan/backend-proartisan/artisan queue:work --sleep=3 --tries=3 --max-time=3600 --memory=512 --timeout=120
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=4
redirect_stderr=true
stdout_logfile=/var/log/supervisor/prosartisan-worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=3600
stopsignal=QUIT
