graph TD
    A[Client] -- 1. Paiement Global (CFA) --> P(Plateforme ProsArtisan)
    P -- 2a. Émission Jeton Matériel --> J{SÉQUESTRE}
    P -- 2b. Avance Main d'œuvre --> MM[Mobile Money Artisan]
    
    J -- 3. QR Code / Code USSD --> Q(Quincaillerie / Fournisseur)
    Q -- 4. Livraison Matériaux --> Art[Artisan sur Chantier]
    
    Art -- 5. Photo Preuve / Validation --> P
    P -- 6. Libération Reliquat Main d'œuvre --> MM
    Q -- 7. Paiement Réel Jeton --> Q